### ISSUE TITLE
Python 3.3 issues

### ISSUE THREAD

**Issue by drdhaval2785** [mnielsen/neural-networks-and-deep-learning#14]
I loved your book.
I tried to run the code network.py as advised by you in the instructions.
The only difference which I made was changing cPickle to pickle and data path to   
```
 f = gzip.open('data/mnist.pkl.gz', 'rb')
```
in mnist_loader.py.

I could load the module fine.

```
>>> import mnist_loader
>>> training_data, validation_data, test_data = \
... mnist_loader.load_data_wrapper()
```
This step gave me this unexpected result.

![capture](https://cloud.githubusercontent.com/assets/5755132/6076396/06d0cdb8-ae09-11e4-83f1-f1a1441ab10d.PNG)

Am I doing something the wrong way ?

**Comment by mnielsen** [comment]
You shouldn't change the path.

Are you running the python shell in the src/ directory?  I'm guessing you're not, and that's the problem (and the fact that you changed the path).

**Comment by drdhaval2785** [comment]
I downloaded and installed python 2.7 instead and it is working as
described in book (even with path changes mentioned earlier in question).

So the issue doesnt seem to be about path.

But anyways, the question doesnt survive.

**Comment by lcddrm** [comment]
Why is this closed without an answer?...
The solution is the following: It seems, that the dataset uses "latin-1" codec. I don't really know why Python3 pickle doesn't recognize this automatically, but you can fix it by loading the data with:
```
with gzip.open("youpath", 'rb') as f:
      training_data, validation_data, test_data = pickle.load(f,encoding="latin-1")
```

**Comment by mnielsen** [comment]
Because the repo is written for Python 2.6/2.7.

**Comment by jmcandrews** [comment]
Has anyone found faulty results when using the latin-1 encoding?

train, valid, test = pickle.load(f, encoding='latin-1')

**Comment by vaibhavravi** [comment]
Yes,

Using the latin1 encoding, I am only getting an accuracy of 389/10000 which is absurd
