### ISSUE TITLE
`numpy.vectorize` only slows the network down.

### ISSUE THREAD

**Issue by pyos** [mnielsen/neural-networks-and-deep-learning#16]
So I was browsing the numpy documentation, and there was this bit about `vectorize`:

>The vectorize function is provided primarily for convenience, not for performance. The implementation is essentially a for loop.

The thing is, absolutely nothing in `sigmoid` requires this convenience: addition, subtraction, division, multiplication, and exponentiation are all performed element-wise on numpy arrays by default, without the need to vectorize the function. In fact, looks like it's better to *not* vectorize it: after removing just these two lines of code, the training process became about 5 times faster on my Chromebook!

**Comment by mnielsen** [comment]
Ah, that's really interesting.  I knew vectorize was basically a for loop, but hadn't put two and two together that it'd be much better to revert to the completely unvec'ed form.  I'll make the change sometime soon.  (Just got back from vacation, lots to sort out.)

**Comment by paipai880429** [comment]
@mnielsen Hi mniselsen, I have been very looking forward to your next sections of "neural network and deep learning" online book ! For the past 3 months, I went to the website to check if there is a update nearly everyday. So when will it be updated? It seems that the last update is last year .

**Comment by mnielsen** [comment]
It'll be updated when the last chapter is ready.  I have no release date set.
