### ISSUE TITLE
Unexpected output for feedward method in Network class

### ISSUE THREAD

**Issue by ZhaozhiQIAN** [mnielsen/neural-networks-and-deep-learning#19]
Hi mnielsen,

It seems that the output for feedward method in Network class is a little bit strange. Here's a reproducible example (assuming Network.py is imported as nw).
```
>>> net1 = nw.Network([2,3,3])
>>> print net1.feedforward([1,1])
[[ 0.41211299  0.64425218  0.61182158]
 [ 0.16157087  0.18549504  0.18942689]
 [ 0.89317608  0.77546557  0.79776741]]
```
As I understand, the output should be a vector containing three elements. 

This might be caused by the init method of Network class where self.biases is defined as a list of (N,1) arrays. However the matrix product np.dot(w, a) in line 41 will return a (N, ) vector.
```
a = sigmoid_vec(np.dot(w, a)+b)
```
NumPy uses broadcasting for array addition which causes the previous error. Using the following line of code in the init method might solve this problem.
```
self.bias = [np.random.randn(x, ) for x in size[1:]]
```

Hope it helps and thanks for the great book!
Zhaozhi

**Comment by mnielsen** [comment]
The inputs are intended to be (n, 1) arrays, not (n,) arrays, as in your example.

(Arguably this is a mistaken initial design decision on my part.  But it was taken intentionally.)

**Comment by liudragonfly** [comment]
bias is a vector, we should create it by np.random.randn(y) instead of np.random.randn(y, 1)
