### ISSUE TITLE
Accuracy options

### ISSUE THREAD

**Issue by drdhaval2785** [mnielsen/neural-networks-and-deep-learning#21]
It would be great if we can provide a flag in the accuracy function of network2.py which allows the user to set the accuracy level.

e.g. The user may like to take the one / two / three / four most activated output neuron to compare his results against.

e.g. The accuracy when I take the highest activated neuron is let's say 78.5
I would like to check how far off my network is.
For that, I would like to check the accuracy with the option that the two most activated neourn in the output layer be checked against my desired output. It it increases to 94.6, this means that the first two guesses are better than the first guess alone.

If some flag can be given in accuracy function, e.g. Comparewith=1 (maybe set 2,3,4 etc), that would be great.

Hope I am clear about what I am asking.

**Comment by mnielsen** [comment]
You should feel free to add this in your own fork.  I'm not going to add the feature, per the comments in Readme.md.
