### ISSUE TITLE
Exercise solutions

### ISSUE THREAD

**Issue by drdhaval2785** [mnielsen/neural-networks-and-deep-learning#22]
The learning schedule is given as an exercise.
It is good to give exercises, but for people who are challenged by the language (python), it would be great if the solved examples and their usages are shown in the repository in maybe a separate folder (if placing in the same folder makes it inconsistent with the book).

Similarly many other issues are given as exercises.
If their solutions can be given in the folder, it would be boon to many people.

**Comment by mnielsen** [comment]
I don't have time (or interest) in doing this.
