### ISSUE TITLE
Storing the network

### ISSUE THREAD

**Issue by drdhaval2785** [mnielsen/neural-networks-and-deep-learning#25]
After experimenting, we usually settle on some structure and some hyper parameters of the network.
It would be great if you can show how we can transfer the weight / bias / layers / neurons / hyper parameters etc to some log file.
Otherwise it would be painful to train a network for long and not being able to store network for future use.
Right now when I close my terminal, the trained network is gone.

**Comment by mnielsen** [comment]
Ditto my response to your earlier issues.
