### ISSUE TITLE
save bug

### ISSUE THREAD

**Issue by drdhaval2785** [mnielsen/neural-networks-and-deep-learning#26]
trying to save the network with save method of network2.py gives the following error

```
>>> net.save('networkstore.txt')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "network2.py", line 295, in save
    "cost": str(self.cost.__name__)}
AttributeError: CrossEntropyCost instance has no attribute '__name__'
```

**Comment by jon--lee** [comment]
I can't seem to replicate your issue. Can you share any more information?

**Comment by drdhaval2785** [comment]
It seems that I am seeing this error message when the network is initialised as 
```
>>> net = network2.Network([784, 30, 10], cost=network2.CrossEntropyCost())
```
and
it is not seen when the network is not initialised like the following
e.g.
```
>>> net = network2.Network([784, 30, 10])
```

The first approach is seen in book chapter 3.

No idea wheher it has something to do with the `cost` parameter or my python version `2.7.6`

**Comment by jon--lee** [comment]
Okay I think see the issue.
It looks like in the first line that you're passing the cost parameter an instance of `CrossEntropyCost` but if you look at the code in network2.py, `init` just wants the class, not an instance of the class. Try removing those extra parentheses so that it's just
```
>>> net = network2.Network([784, 30, 10], cost=network2.CrossEntropyCost)
```
At least that's how it's written in Chapter 3. Anyone feel free to correct me if I'm wrong.
@mnielsen can we close this issue?

**Comment by mnielsen** [comment]
@jon--lee Yes, that's right, it's the class not an instance which is to be passed.

**Comment by drdhaval2785** [comment]
![screenshot from 2015-07-11 12 54 23](https://cloud.githubusercontent.com/assets/5755132/8632885/043ccfe2-27cc-11e5-983e-855d0dd89a72.png)

This is the place from where i copied the code for execution.
It indeed has one instance.
All others have class.

maybe this requires correction.

**Comment by mnielsen** [comment]
Ah, many thanks: that is indeed an error in the book's text.   I will correct in the next update to the site.

(In a much earlier version of the code it was necessary to generate an instance.  I guess this is probably a holdover from that time.)
