### ISSUE TITLE
Bisecting data for Feature Mapping

### ISSUE THREAD

**Issue by samrusk** [mnielsen/neural-networks-and-deep-learning#29]
Hi,

First of all, thank you for putting this code together!  It's clean and runs great.

I am working on my own application forked from your code base and have come into a question regarding splitting the input data in the first layer.  If you wanted to create a set of feature maps from different parts of the input data, for example creating a set of convolutional maps from all of the pixels on the left side of the image and another set from the pixels on the right side of the image, is there a way that you know to do this?

Because the tensor objects are not initialized yet in the layer objects, it seems difficult to make custom layers before inputing them into the network.

Hope to get some feedback and thanks again.

Sam

**Comment by mnielsen** [comment]
Glad you find the code useful.  I'm afraid I can't help with spin-off projects - it's a question of keeping my own time commitment to this under control, I hope you understand.  Take a look at the Theano docs and mailing list.
