### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by iamcodylee** [mnielsen/neural-networks-and-deep-learning#35]
I'm working on python 3.4, when I run the code below

import mnist_loader
import network

training_data, validation_data,test_data = mnist_loader.load_data_wrapper()
net = network.Network([783,30,10])
net.SGD(training_data, 30, 10, 3.0, test_data=test_data)

and I get wrong message as 
   training_data, validation_data, test_data = pickle.load(f)
UnicodeDecodeError: 'ascii' codec can't decode byte 0x90 in position 614: ordinal not in range(128)

tried to add "encoding='utf-8'" into pickle.load(f), but it still doesn't work, can you help me?

**Comment by etillett** [comment]
I was having the same error last night, I just found this (I'm at work atm):

http://stackoverflow.com/questions/28218466/unpickling-a-python-2-object-with-python-3

which might work.  I was about to just load up 2.7 and work through it from there it I couldn't figure it out though.

**Comment by mnielsen** [comment]
Python 3 and Python 2 don't pickle objects in the same way.  The code is written for Python 2.7, so that's likely the issue.

**Comment by selahlynch** [comment]
I too am trying to run this code in Python 3.  Modifying cPickle.load(f) to cPickle.load(f, encoding='iso-8859-1') seems to have fixed my issues.

**Comment by vaibhavravi** [comment]
@selahlynch this read the data fine but resulted in poor accuracy.
