### ISSUE TITLE
Exception when running network.py with different number of hidden neurons

### ISSUE THREAD

**Issue by ft-malik** [mnielsen/neural-networks-and-deep-learning#36]
Hi,

First of all thanks for this great book.

I tried to run your first network (network.py) with boolean datas but I have a numpy issue, here is my code:
```

import numpy as np
from network import Network

datas = [
    (np.array([0,0]),0),
    (np.array([0,1]),1),
    (np.array([1,0]),1),
    (np.array([1,1]),1)
]


net = Network([2, 3, 2])
net.SGD(datas, 10000000, 2, 0.0001, datas)

```

and here is the Exception

> Traceback (most recent call last):
>   File "main.py", line 13, in <module>
>     net.SGD(datas, 10000000, 2, 0.0001, datas)
>   File "network.py", line 62, in SGD
>     self.update_mini_batch(mini_batch, eta)
>   File "network.py", line 77, in update_mini_batch
>     delta_nabla_b, delta_nabla_w = self.backprop(x, y)
>   File "network.py", line 117, in backprop
>     nabla_w[-l] = np.dot(delta, activations[-l-1].transpose())
> ValueError: shapes (3,3) and (2,) not aligned: 3 (dim 1) != 2 (dim 0)
>

**Comment by ft-malik** [comment]
May I have some info on why this is closed ?
It may be obvious but I missed it :) sorry

**Comment by mnielsen** [comment]
This isn't a bug, and I'm not providing free-of-charge assistance debugging other people's neural nets.

**Comment by ft-malik** [comment]
ok, thanks
