### ISSUE TITLE
cPickle dependency?

### ISSUE THREAD

**Issue by polycopter** [mnielsen/neural-networks-and-deep-learning#41]
(this is an issue with the book, not really the code)
I don't believe cPickle was ever specified as a dependency before I got to this point in the chapter:

D:\src\py\neural-networks-and-deep-learning\src>python
Python 3.4.1 (v3.4.1:c0e311e010fc, May 18 2014, 10:45:13) [MSC v.1600 64 bit (AM
D64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> **import mnist_loader**
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\src\py\neural-networks-and-deep-learning\src\mnist_loader.py", line 1
3, in <module>
    import cPickle
ImportError: No module named 'cPickle'
>>> exit()

D:\src\py\neural-networks-and-deep-learning\src>pip install cPickle
Downloading/unpacking cPickle
  Could not find any downloads that satisfy the requirement cPickle
Cleaning up...
No distributions at all found for cPickle

**Comment by polycopter** [comment]
upon reflection, this doesn't belong here (actually, the code is listed in the chapter, it shows the import cPickle line)

**Comment by arpit1997** [comment]
you have to install Theano package in order to solve this problem
`$ pip3 install theano `
and then change `import cPickle` to `import six.moves.cPickle`
