### ISSUE TITLE
SGD functions do not take lists of tuplets as training data.

### ISSUE THREAD

**Issue by chibill** [mnielsen/neural-networks-and-deep-learning#43]
In the code and also the book it says that the SGD function takes a list of tuplets as training data. But this is not the case.

In the code it is documented as 

`Train the neural network using mini-batch stochastic gradient
        descent.  The ``training_data`` is a list of tuples ``(x, y)``
        representing the training inputs and the desired outputs.`

But when given a list of tuplets it throws the following error.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/private/var/mobile/Containers/Shared/AppGroup/86CA80D9-51E6-4CE7-84F4-071E64185046/Documents/mystuff/neural-networks-and-deep-learning-master/src/network2.py", line 166, in SGD
    mini_batch, eta, lmbda, len(training_data))
  File "/private/var/mobile/Containers/Shared/AppGroup/86CA80D9-51E6-4CE7-84F4-071E64185046/Documents/mystuff/neural-networks-and-deep-learning-master/src/network2.py", line 201, in update_mini_batch
    delta_nabla_b, delta_nabla_w = self.backprop(x, y)
  File "/private/var/mobile/Containers/Shared/AppGroup/86CA80D9-51E6-4CE7-84F4-071E64185046/Documents/mystuff/neural-networks-and-deep-learning-master/src/network2.py", line 240, in backprop
    nabla_w[-l] = np.dot(delta, activations[-l-1].transpose())
AttributeError: 'list' object has no attribute 'transpose'

**Comment by mnielsen** [comment]
Can you provide a minimal but complete working example of what you're trying to do?

**Comment by mnielsen** [comment]
Which chapter / version of the SGD function?

**Comment by chibill** [comment]
Chapter 1 and also the doc notes in network.py and network2.py

**Comment by chibill** [comment]
Sorry hit the wrong button

**Comment by mnielsen** [comment]
Loaded the training data as per chapter 1, checked types, they were a list and a tuple, as prescribed.

**Comment by chibill** [comment]
Well I load the training data it is always of type ndarray from numpy. I will post a pic if what I am getting.

**Comment by mnielsen** [comment]
![image](https://cloud.githubusercontent.com/assets/52171/14871622/fdccbf3e-0cb1-11e6-8c38-4206ef5eedd8.png)

**Comment by mnielsen** [comment]
![image](https://cloud.githubusercontent.com/assets/52171/14871630/137f1ea8-0cb2-11e6-9235-220db0953e48.png)

**Comment by chibill** [comment]
Okay well this is so weird... When I was trying this out two days ago everything was being numpy arrays... Now when I run the same exact script it runs with out problem.... I think my python interpreter was bugged up. 

Sorry to have bothered you.

**Comment by mnielsen** [comment]
No worries.  I've definitely had similar experiences to yours in the past - it can be very frustrating.

**Comment by chibill** [comment]
Just a question what do I fill the tuplet with. In the training data from here the tuplet has the two parts as numpy.ndarray (which I have no idea how to use.)

**Comment by wudenggang0** [comment]
Maybe you can change the load_data_wrapper() in file mnist_loader.py：
`training_data = zip(training_inputs, training_results)` ->`training_data = list(zip(training_inputs, training_results))` 
`validation_data = zip(validation_inputs, va_d[1])`->`validation_data = list(zip(validation_inputs, va_d[1]))`
`test_data = zip(test_inputs, te_d[1])`->`test_data = list(zip(test_inputs, te_d[1]))`
