### ISSUE TITLE
how to predict in single way ?

### ISSUE THREAD

**Issue by szad670401** [mnielsen/neural-networks-and-deep-learning#44]
I don't know about Theano.
the function SGD seems finish the Training Validate and Test automatically .
but the Network Class does't have a function for predicting a single vector from image.

**Comment by mnielsen** [comment]
I'm not able to assist with extensions to the code, though if others wish to jump in, by all means.

(I actually don't understand the question.)

**Comment by reynoldscem** [comment]
I believe szad670401 is referring to the fact that the function SGD in your code will evaluate the model on test data each epoch if it is given as an argument (which is optional).

Szad670401, you can evaluate the network through one of the two methods (depending on what you'd like output):
https://github.com/mnielsen/neural-networks-and-deep-learning/blob/master/src/network.py#L38
https://github.com/mnielsen/neural-networks-and-deep-learning/blob/master/src/network.py#L120
