### ISSUE TITLE
win64 or win32

### ISSUE THREAD

**Issue by Jayhello** [mnielsen/neural-networks-and-deep-learning#47]
my system is win64 ,i can't use your code directly 。is you code use in win32?

**Comment by xzblueofsky** [comment]
i use ubuntu14.04








赵昕

工程师

格灵深瞳










 
 
 
------------------ Original ------------------

**Comment by Jayhello** [comment]
thank you ,i know the problem.

**Comment by willshion** [comment]
chinese?
