### ISSUE TITLE
random.shuffle() repeats data in single batch

### ISSUE THREAD

**Issue by erobic** [mnielsen/neural-networks-and-deep-learning#50]
I tested `network2.py` with a simple AND gate.

With `training_data` of size 4 and `mini_batch_size`=4, I was expecting that each `mini_batch` would use all of the sample data. However, since `random.shuffle(training_data)` actually repeated some elements of `training_data` in same batch, I got strange messages like:

> Accuracy on training data: 4 / 4
> Accuracy on evaluation data: 3 / 4

This was strange because I expected the training data and evaluation data to be the same.

Anyway, using `np.random.shuffle()` instead of `random.shuffle()` fixed the problem.

Is repeating training data in a batch intentional?

Test code:

```
import numpy as np
import network2

training_data = np.array([
        [[[0.0], [0.0]], [[1.0], [0.0]]],
        [[[0.0], [1.0]], [[1.0], [0.0]]],
        [[[1.0], [0.0]], [[1.0], [0.0]]],
        [[[1.0], [1.0]], [[0.0], [1.0]]]
    ])

evaluation_data = [
        [[[0.0], [0.0]], 0],
        [[[0.0], [1.0]], 0],
        [[[1.0], [0.0]], 0],
        [[[1.0], [1.0]], 1]
    ]

net = network2.Network([2, 10, 2])
net.SGD(training_data, epochs=1000, mini_batch_size=4, eta=0.1,
        lmbda=1,
        evaluation_data=evaluation_data,
        monitor_evaluation_cost=True,
        monitor_evaluation_accuracy=True,
        monitor_training_cost=True,
        monitor_training_accuracy=True)
```

**Comment by mnielsen** [comment]
As far as I can see, there's no bug here - random.shuffle works just fine on a list of tuples.
