### ISSUE TITLE
Decreasing detection - not sure if this is right

### ISSUE THREAD

**Issue by adicirstei** [mnielsen/neural-networks-and-deep-learning#52]
Hi,

I ported the first chapter's code to F# and started training a network with 
784 - 60 - 30 - 10 neurons, 100 epochs, eta 30, minibatch 10.

Does the bellow output look right? If not, what I might have got wrong? 

```
Running epoch	1 /	100 | 8182 / 10000
Running epoch	2 /	100 | 7753 / 10000
Running epoch	3 /	100 | 7298 / 10000
Running epoch	4 /	100 | 7182 / 10000
Running epoch	5 /	100 | 6698 / 10000
Running epoch	6 /	100 | 6489 / 10000
Running epoch	7 /	100 | 6721 / 10000
Running epoch	8 /	100 | 6812 / 10000
Running epoch	9 /	100 | 6933 / 10000
Running epoch	10 /	100 | 6655 / 10000
Running epoch	11 /	100 | 6330 / 10000
Running epoch	12 /	100 | 6574 / 10000
Running epoch	13 /	100 | 6781 / 10000
Running epoch	14 /	100 | 6929 / 10000
Running epoch	15 /	100 | 7159 / 10000
Running epoch	16 /	100 | 7206 / 10000
Running epoch	17 /	100 | 7017 / 10000
Running epoch	18 /	100 | 6021 / 10000
Running epoch	19 /	100 | 6617 / 10000
Running epoch	20 /	100 | 6106 / 10000
Running epoch	21 /	100 | 5529 / 10000
Running epoch	22 /	100 | 6026 / 10000
Running epoch	23 /	100 | 5341 / 10000
Running epoch	24 /	100 | 5962 / 10000
Running epoch	25 /	100 | 5656 / 10000
Running epoch	26 /	100 | 5743 / 10000
Running epoch	27 /	100 | 5677 / 10000
Running epoch	28 /	100 | 6381 / 10000
Running epoch	29 /	100 | 6240 / 10000
Running epoch	30 /	100 | 6634 / 10000
Running epoch	31 /	100 | 5936 / 10000
```

Thanks, 
Adrian

**Comment by MathLee** [comment]
I think your eta is too big,maybe eta 5 and your rescult will be better.


 在2016年10月1日 20:40:27, adicirstei <notifications@github.com> 写道：



Hi,

I ported the first chapter's code to F# and started training a network with
784 - 60 - 30 - 10 neurons, 100 epochs, eta 30, minibatch 10.

Does the bellow output look right? If not, what I might have got wrong?

Running epoch   1 / 100 | 8182 / 10000
Running epoch   2 / 100 | 7753 / 10000
Running epoch   3 / 100 | 7298 / 10000
Running epoch   4 / 100 | 7182 / 10000
Running epoch   5 / 100 | 6698 / 10000
Running epoch   6 / 100 | 6489 / 10000
Running epoch   7 / 100 | 6721 / 10000
Running epoch   8 / 100 | 6812 / 10000
Running epoch   9 / 100 | 6933 / 10000
Running epoch   10 /    100 | 6655 / 10000
Running epoch   11 /    100 | 6330 / 10000
Running epoch   12 /    100 | 6574 / 10000
Running epoch   13 /    100 | 6781 / 10000
Running epoch   14 /    100 | 6929 / 10000
Running epoch   15 /    100 | 7159 / 10000
Running epoch   16 /    100 | 7206 / 10000
Running epoch   17 /    100 | 7017 / 10000
Running epoch   18 /    100 | 6021 / 10000
Running epoch   19 /    100 | 6617 / 10000
Running epoch   20 /    100 | 6106 / 10000
Running epoch   21 /    100 | 5529 / 10000
Running epoch   22 /    100 | 6026 / 10000
Running epoch   23 /    100 | 5341 / 10000
Running epoch   24 /    100 | 5962 / 10000
Running epoch   25 /    100 | 5656 / 10000
Running epoch   26 /    100 | 5743 / 10000
Running epoch   27 /    100 | 5677 / 10000
Running epoch   28 /    100 | 6381 / 10000
Running epoch   29 /    100 | 6240 / 10000
Running epoch   30 /    100 | 6634 / 10000
Running epoch   31 /    100 | 5936 / 10000


Thanks,
Adrian

**Comment by adicirstei** [comment]
You are right, I meant 3.0. My mistake.

**Comment by MathLee** [comment]
So sorry for replying you after a long time.I have thought a long time for your question.In my opinion,you add another layer to the netwok and you should decrease your eta maybe 0.1 is suitable.I hope my advice can soulve your problem.


On 10/02/2016 02:46, adicirstei wrote:

You are right, I meant 3.0. My mistake.
