### ISSUE TITLE
Porting from Python 2.7 to 3.5

### ISSUE THREAD

**Issue by prithwis** [mnielsen/neural-networks-and-deep-learning#56]
This is not an "issue" as such. I have just documented where all the programs need to be changed so that they work work on Python 3
----------------------------------------------------------------------------------------
mnist_loader.py

#import cPickle				# -- py2
import _pickle as cPickle		        # -- py3

#training_data, validation_data, test_data = cPickle.load(f)			                # -- py2
training_data, validation_data, test_data = cPickle.load(f, encoding="latin1")	# -- py3

#training_data = zip(training_inputs, training_results) 			# -- py2
training_data = list(zip(training_inputs, training_results))		# -- py3
   
#validation_data = zip(validation_inputs, va_d[1])				# -- py2
validation_data = list(zip(validation_inputs, va_d[1]))			# -- py3

#test_data = zip(test_inputs, te_d[1])					# -- py2
test_data = list(zip(test_inputs, te_d[1]))					# -- py3

-----------------------------------------------------------------------------------------------------
network.py

#for j in xrange(epochs):					# -- py2
for j in range(epochs):					# -- py3

#for k in xrange(0, n, mini_batch_size)]		# -- py2
for k in range(0, n, mini_batch_size)]		# -- py3

#for l in xrange(2, self.num_layers):			# -- py2
for l in range(2, self.num_layers):				# -- py3

--------------------------------------------------------------------------------------------------
hope this helps those who would like to work with Python3

**Comment by MichalDanielDobrzanski** [comment]
I recommed my repository where I changed everything to work with Python3.5 (network.py, network2.py, network3.py). Currently, I am working on trying to port expand_mnist_data

https://github.com/MichalDanielDobrzanski/DeepLearningPython35

**Comment by mnielsen** [comment]
Thanks for this.  I don't plan to maintain forward compatibility with Python 3.  However, I've just added a note to the repo README pointing to MichalDanielDobrzanski's Python 3 repo. I hope that's okay?
