### ISSUE TITLE
ImportError when running network3

### ISSUE THREAD

**Issue by a798253982** [mnielsen/neural-networks-and-deep-learning#68]
`ImportError: ('The following error happened while compiling the node', ConvOp{('imshp', (1, 28, 28)),('kshp', (5, 5)),('nkern', 20),('bsize', 10),('dx', 1),('dy', 1),('out_mode', 'valid'),('unroll_batch', 5),('unroll_kern', 2),('unroll_patch', False),('imshp_logical', (1, 28, 28)),('kshp_logical', (5, 5)),('kshp_logical_top_aligned', True)}(Reshape{4}.0, <TensorType(float64, 4D)>), '\n', '/home/ltt/.theano/compiledir_Linux-4.8--generic-x86_64-with-debian-stretch-sid-x86_64-2.7.13-64/tmpfQr0J4/8d91b12cea0f84d7d64f27847cc49374.so: undefined symbol: _ZNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEED1Ev', "[ConvOp{('imshp', (1, 28, 28)),('kshp', (5, 5)),('nkern', 20),('bsize', 10),('dx', 1),('dy', 1),('out_mode', 'valid'),('unroll_batch', 5),('unroll_kern', 2),('unroll_patch', False),('imshp_logical', (1, 28, 28)),('kshp_logical', (5, 5)),('kshp_logical_top_aligned', True)}(<TensorType(float64, (False, True, False, False))>, <TensorType(float64, 4D)>)]")`

Ubuntu16.04, python 2.7, theano 0.7

**Comment by roholazandie** [comment]
I had the same problem.It's related to gcc. The best solution for you is to upgrade to the latest version of Theano first, and then follow this link to install g++ 4.9:
http://deeplearning.net/software/theano/install_ubuntu.html#prerequisites-through-system-packages-not-recommended
The only remaining problem is changing this import:
`from theano.tensor.signal import downsample`
to
`from theano.tensor.signal import pool`
and finally change:
`downsample.max_pool_2d()` 
to
`pool.pool_2d()`

**Comment by a798253982** [comment]
Thank you !
