### ISSUE TITLE
What part of the code controls parallelism?

### ISSUE THREAD

**Issue by queirozfcom** [mnielsen/neural-networks-and-deep-learning#69]
I notice that all my CPU cores are used when, for instance, I call `SGD()` on `network2`. However, I didn't find any calls to `joblib` or `Parallel` in the code. How is this parallelism being controlled?

**Comment by aedancullen** [comment]
The parallelism in `network2` is handled by the BLAS library that `numpy` is using. In the case that it's using a BLAS implementation that can take advantage of multiple cores (both OpenBLAS and ATLAS can, for example), `numpy` does this silently. (See [https://scipy.github.io/old-wiki/pages/ParallelProgramming](https://scipy.github.io/old-wiki/pages/ParallelProgramming)).
