### ISSUE TITLE
random.shuffle with numpy <Line 51>

### ISSUE THREAD

**Issue by gufengxiaoyuehan** [mnielsen/neural-networks-and-deep-learning#73]
when trying your code line by line with the tutorial [CHAPTER 1 Using neural nets to recognize handwritten digits](http://neuralnetworksanddeeplearning.com/chap1.html). I think the random.shuffle do a little tricky beyond you intention. it will generate the sample with replacement. as this link showing https://github.com/numpy/numpy/issues/1655. so it show be numpy.random.shuffle or I make a wrong understand of the essay.

**Comment by mnielsen** [comment]
You may be right, but I've moved on to other things, and aren't going to look into it.

**Comment by gufengxiaoyuehan** [comment]
bad news to me.  your book help me better understanding the concept for deep learning,  thanking any way. and good lucks.
