### ISSUE TITLE
theano memory leak in network3.py

### ISSUE THREAD

**Issue by jheinecke** [mnielsen/neural-networks-and-deep-learning#74]
Hi, thanks for the great tutorial!
I just played around with the CNN example code (network3.py). It works well with theano 0.8.2, but not with theano 0.9.0. In the latter case memory goes up through the roof immediately. This seems to be a theano problem (see also https://github.com/Theano/Theano/issues/5810)
I use 
- Ubuntu 16.04, no Blas installed
- sudo pip install theano==0.8.2
- numpy 1.11
- scipy 0.17
- python 2.7

Best regards
Johannes

**Comment by mnielsen** [comment]
Theano 0.9.2 is not supported.
